const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./models/Product');

dotenv.config();

const products = [
  {
    name: 'Classic White Oxford Shirt',
    description: 'A timeless white oxford shirt crafted from premium cotton. Perfect for formal and casual occasions.',
    price: 1299,
    originalPrice: 1999,
    category: 'clothing',
    subCategory: 'Shirts',
    brand: 'StyleCo',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600',
    stock: 50,
    featured: true,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['White', 'Light Blue'],
    tags: ['formal', 'casual', 'cotton'],
  },
  {
    name: 'Slim Fit Chino Pants',
    description: 'Modern slim fit chinos made from stretch cotton blend. Versatile and comfortable for all-day wear.',
    price: 1799,
    originalPrice: 2499,
    category: 'clothing',
    subCategory: 'Pants',
    brand: 'UrbanEdge',
    image: 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600',
    stock: 35,
    featured: true,
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Beige', 'Navy', 'Olive'],
    tags: ['casual', 'office', 'slim fit'],
  },
  {
    name: 'Oversized Graphic Tee',
    description: 'Trendy oversized graphic tee made from 100% organic cotton. A streetwear essential.',
    price: 799,
    originalPrice: 1199,
    category: 'clothing',
    subCategory: 'T-Shirts',
    brand: 'StreetVibe',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600',
    stock: 80,
    featured: false,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Black', 'White', 'Grey'],
    tags: ['streetwear', 'casual', 'organic'],
  },
  {
    name: 'Floral Summer Dress',
    description: 'A beautiful floral print summer dress with a flowy silhouette. Light, breezy and perfect for warm days.',
    price: 1599,
    originalPrice: 2299,
    category: 'clothing',
    subCategory: 'Dresses',
    brand: 'BloomWear',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=600',
    stock: 25,
    featured: true,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Pink Floral', 'Blue Floral'],
    tags: ['summer', 'floral', 'casual'],
  },
  {
    name: 'Denim Jacket',
    description: 'Classic denim jacket with a modern cut. Durable, stylish and a wardrobe staple for every season.',
    price: 2499,
    originalPrice: 3499,
    category: 'clothing',
    subCategory: 'Jackets',
    brand: 'DenimCo',
    image: 'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=600',
    stock: 20,
    featured: true,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Blue', 'Black'],
    tags: ['denim', 'jacket', 'casual'],
  },
  {
    name: 'Samsung Galaxy S24',
    description: 'Latest Samsung flagship with a 50MP camera, 6.2 inch Dynamic AMOLED display and 5000mAh battery.',
    price: 74999,
    originalPrice: 84999,
    category: 'electronics',
    subCategory: 'Smartphones',
    brand: 'Samsung',
    image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=600',
    stock: 15,
    featured: true,
    colors: ['Phantom Black', 'Cream', 'Violet'],
    tags: ['smartphone', 'android', 'flagship'],
  },
  {
    name: 'Apple AirPods Pro',
    description: 'Premium wireless earbuds with Active Noise Cancellation, Transparency mode and spatial audio.',
    price: 24999,
    originalPrice: 26900,
    category: 'electronics',
    subCategory: 'Audio',
    brand: 'Apple',
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600',
    stock: 30,
    featured: true,
    colors: ['White'],
    tags: ['earbuds', 'wireless', 'noise cancellation'],
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    description: 'Industry leading noise cancelling headphones with 30 hours battery life and premium sound quality.',
    price: 29990,
    originalPrice: 34990,
    category: 'electronics',
    subCategory: 'Audio',
    brand: 'Sony',
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600',
    stock: 18,
    featured: false,
    colors: ['Black', 'Silver'],
    tags: ['headphones', 'noise cancelling', 'wireless'],
  },
  {
    name: 'MacBook Air M2',
    description: 'Supercharged by M2 chip with 8-core CPU, 8-core GPU, 8GB RAM and 256GB SSD. Fanless and ultraportable.',
    price: 114900,
    originalPrice: 119900,
    category: 'electronics',
    subCategory: 'Laptops',
    brand: 'Apple',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600',
    stock: 10,
    featured: true,
    colors: ['Midnight', 'Starlight', 'Space Grey'],
    tags: ['laptop', 'apple', 'ultrabook'],
  },
  {
    name: 'OnePlus Nord Buds 2',
    description: 'True wireless earbuds with 12.4mm drivers, ANC, 36 hours total battery and IP55 water resistance.',
    price: 3499,
    originalPrice: 4999,
    category: 'electronics',
    subCategory: 'Audio',
    brand: 'OnePlus',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600',
    stock: 45,
    featured: false,
    colors: ['White', 'Black'],
    tags: ['earbuds', 'anc', 'budget'],
  },
  {
    name: 'Casual Sneakers',
    description: 'Lightweight and comfortable sneakers with memory foam insoles. Perfect for everyday wear.',
    price: 2199,
    originalPrice: 2999,
    category: 'clothing',
    subCategory: 'Footwear',
    brand: 'StepUp',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600',
    stock: 40,
    featured: false,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: ['White', 'Black', 'Red'],
    tags: ['sneakers', 'casual', 'comfortable'],
  },
  {
    name: 'Smart Watch Series X',
    description: 'Feature-packed smartwatch with health monitoring, GPS, 7 day battery and always-on AMOLED display.',
    price: 8999,
    originalPrice: 12999,
    category: 'electronics',
    subCategory: 'Wearables',
    brand: 'TechWear',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600',
    stock: 22,
    featured: true,
    colors: ['Black', 'Silver', 'Rose Gold'],
    tags: ['smartwatch', 'fitness', 'wearable'],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('MongoDB Connected');
    await Product.deleteMany({});
    console.log('Old products cleared');
    await Product.insertMany(products);
    console.log(`${products.length} products added successfully!`);
    process.exit(0);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedDB();